version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo Running database migrations...
      - python manage.py migrate

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-django-app .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)  # Modify region as needed
      - docker tag my-django-app:latest <your-account-id>.dkr.ecr.<region>.amazonaws.com/my-django-app:latest
      - docker push <your-account-id>.dkr.ecr.<region>.amazonaws.com/my-django-app:latest
